#include <stdio.h>
#include <locale.h>
#include <stdio.h>
#include <wchar.h>      /* wint_t */
#include <limits.h>
int ft_printf(const char* format, ...);

// void test_bigint()
// {
//     char *output;
// 	char *to_add;

//     output = malloc(99999*sizeof(char));
// 	to_add = malloc(99999*sizeof(char));
//     output = ft_strcpy(output, "2001.1003");
// 	to_add = ft_strcpy(to_add, "999999");
//     printf("multiply : %s by two\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("result :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
// 	output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
// 	output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
// 	output = ft_bigint_add(output, to_add);
// 	printf("add  999999:\t%s\n", output);
// 	to_add = ft_strcpy(to_add, ".1111111");
// 	output = ft_bigint_add(output, to_add);
// 	printf("add  0.1111111:\t%s\n", output);
// 	to_add = ft_strcpy(to_add, "11000030");
// 	output = ft_bigint_add(output, to_add);
// 	printf("add  11000030:\t%s\n", output);
// 	to_add = ft_strcpy(to_add, "10000000000000000000.0");
// 	output = ft_bigint_add(output, to_add);
// 	printf("add  10000000000000000000.0:\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_divide_by_two(output);
//     printf("divide by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
//     output = ft_bigint_multiply_by_two(output);
//     printf("multiply by 2 :\t%s\n", output);
// 	free(output);
// 	free(to_add);
// }

int main(void)
{
	printf("printf :\t%f\n", 10.51111);
	ft_printf("ft_printf :\t%f\n\n", 10.51111);
	printf("printf :\t%f\n", 99.0555);
	ft_printf("ft_printf :\t%f\n\n", 99.0555);
	printf("printf :\t%f\n", 1111.1111111111);
	ft_printf("ft_printf :\t%f\n\n", 1111.1111111111);
	printf("printf :\t%f\n", 1111.777777777777777777);
	ft_printf("ft_printf :\t%f\n\n", 1111.777777777777777777);
	printf("printf :\t%.1f\n", 1111.777777777777777777);
	ft_printf("ft_printf :\t%.1f\n\n", 1111.777777777777777777);
	printf("printf :\t%f\n", 0.0000000005);
	ft_printf("ft_printf :\t%f\n\n", 0.0000000005);
	printf("printf :\t%f\n", 0.02);
	ft_printf("ft_printf :\t%f\n\n", 0.02);
	printf("printf :\t%f\n", 0.0002);
	ft_printf("ft_printf :\t%f\n\n", 0.0002);
	printf("printf :\t%f\n", 0.000004);
	ft_printf("ft_printf :\t%f\n\n", 0.000004);
	printf("printf :\t%f\n", -0.000004);
	ft_printf("ft_printf :\t%f\n\n", -0.000004);
	printf("printf :\t%f\n", 9999999.123456789);
	ft_printf("ft_printf :\t%f\n\n", 9999999.123456789);
	printf("printf :\t%.3f\n", 9999999.123456789);
	ft_printf("ft_printf :\t%.3f\n\n", 9999999.123456789);
    return 0;
}